<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CategoryStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string|unique:categories|min:5|max:75'
        ];
    }

    /**
     * Get de error messages for the defined validation rules
     *
     * @return array
     */
    public function messages()
    {
        return [
            'name.required' => 'De naam is verplicht',
            'name.string' => 'De naam moet tekst bevatten',
            'name.unique' => 'De naam moet uniek zijn',
            'name.min' => 'De naam moet minimaal 5 karakters lang zijn',
            'name.max' => 'De naam moet maximaal 75 karakters lang zijn'
        ];
        //return parent::messages(); // TODO: Change the autogenerated stub
    }
}
